/// Flutter icons Divar
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Divar
///      fonts:
///       - asset: fonts/Divar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Divar {
  Divar._();

  static const _kFontFam = 'Divar';
  static const String? _kFontPkg = null;

  static const IconData divar = IconData(
      0xe800, fontFamily: _kFontFam,);
}
